---
- name: Configurar Jenkins e dependências em um servidor Red Hat AWS
  hosts: slave
  become: true
  tasks:
    - name: Instalar pacotes necessários
      yum:
        name:
          - fontconfig
          - java-17-openjdk
          - git
          - zlib-devel 
          - pam-devel 
          - libtool 
          - bison 
          - flex 
          - autoconf 
          - gcc 
          - make
          - net-tools 
          - lsof
          - tcpdump 
        state: present

    - name: Criar usuário Jenkins
      user:
        name: jenkins
        home: /var/lib/Jenkins
        shell: /bin/bash
        state: present
